[dotter] update dotter to v0.13.4 and add version/sync script

diff --git a/.dotter/bin/dotter b/.dotter/bin/dotter
--- a/.dotter/bin/dotter
+++ b/.dotter/bin/dotter
@@ -3,7 +3,12 @@ set -e
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
 
-VERSION="0.13.3"
+if [ ! -f "$DIR/.dotter-version" ]; then
+	echo "dotter version file (.dotter-version) missing" >&2
+	exit 1
+fi
+
+VERSION="${DOTTER_VERSION:-"$(cat "$DIR/.dotter-version")"}"
 
 if [[ "$OSTYPE" == darwin* ]]; then
   OS=darwin
